import type { Metadata } from "next";
import "./globals.css";
import TitleSection from '@/app/components/TitleSection'

export const metadata: Metadata = {
  title: "HyunminY",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
      <TitleSection/>
        {children}
      </body>
    </html>
  );
}
